[[language]]
name = "typescript"
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
indent = { tab-width = 4, unit = " " }
auto-format = true

[[language]]
name = "rust"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "css"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "html"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "javascript"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "python"
indent = { tab-width = 4, unit = " " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = " " }
